### ISSUE TITLE
Change cluster parameter naming to be consistent

### ISSUE THREAD

**Issue by dsullivan7** [CircleCI-Public/aws-ecs-orb#136]
## Describe Request:
In the `run-task` command, the parameter used to specify the cluster is `cluster`, which matches the aws cli command parameter. However, in `update-service`, the same parameter is called `cluster-name`.  My request is that the `update-service` command support a `cluster` parameter, for both consistency and to match the underlying aws api.

**Comment by gmemstr** [comment]
While I agree, I'd be very cautious about renaming an established parameter, especially since we can't necessarily notify those who may depend on it. In this instance a major change would be required, but the scope of the changes is actually relatively small -- so I suppose to only way to make this happen would be to loop it in with some other major changes to the orb to help justify the major release.
