### ISSUE TITLE
Please update CHANGELOG.md

### ISSUE THREAD

**Issue by yuichiro12** [CircleCI-Public/aws-ecs-orb#78]
so that we can see the new features

**Comment by lokst** [comment]
Definitely @yuichiro12 ! I'll update the changelog soon but I'd just like to let you know quickly as well that there haven't been any major feature changes since the last version listed in the changelog. The orb was recently bumped to a version 1 release to indicate stability, since the orb has been used in many builds.

**Comment by yuichiro12** [comment]
OK I see.
