### ISSUE TITLE
Support verify-revision-is-deployed command when deployment-controller is CODE_DEPLOY

### ISSUE THREAD

**Issue by enokawa** [CircleCI-Public/aws-ecs-orb#93]
## What would you like to be added

Suport verify-revision-is-deployed command when `deployment-controller` parameter is CODE_DEPLOY.

Ref: #34

## Why is this needed

Currently, verify-revision-is-deployed command supported `deployment-controller` parameter is only ECS.  
So I want this feature added.

**Comment by lokst** [comment]
@enokawa Thanks for filing the issue, it'd be great if the `verify-revision-is-deployed` command can support Blue/Green deployments. Do let us know if you are interested in making a PR for this enhancement! 🙂

**Comment by alekhrycaiko** [comment]
@lokst the `verify-revision-is-deployed` command does not accept blue-green to my understanding. 

I do think it'd be a good idea to build something out to rectify this issue. As it is currently, there is no feedback that a blue green deployment times out, nor is there any feedback to when precisely a deploy succeeds or fails and is rolled back. The only error case I've come across currently is when multiple deployments trigger concurrently.

I think it'd be possible to report successful deploys with what's currently available, but, it'd involve some custom implementation. The `DEPLOYMENT_ID` retrieved from building the deployment could be queried over an hour to get the status of the deployment via  `aws deploy get-deployment --deployment-id $DEPLOYMENT_ID`. I'd be interested in having this functionality so that I could easily setup a queue of deployments, and get feedback on when my deployments succeed or error out.

I'd be interested in taking that on with a PR if you're okay with some custom functionality, similar to what I've mentioned above. Happy to hear other ideas too.

**Comment by lokst** [comment]
Thanks @alekhrycaiko, your PR is very welcome! We'll review it as soon as possible.

**Comment by lokst** [comment]
This should be resolved in version 1.3.0 of the orb 🎉
